"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import sys

dirname, filename = os.path.split(os.path.abspath(__file__))
sys.path.append(dirname)
from setuptools import setup
from subprocess import Popen, PIPE

APP_NAME = 'NetworkProfiler'

DATA_FILES = [
    'pytcptrace/tcptrace'
]

OPTIONS = {
    'argv_emulation': True,
    'packages': ['pytcptrace'],
    'iconfile': 'resource/icon.icns',
    'plist': {
        'CFBundleShortVersionString': '1.0.0',
        'CFBundleIconFile': 'icon.icns',
    }
}

setup(
    # Application name
    name=APP_NAME,
    # Entry file
    app=['main.py'],
    # Static data files
    data_files=DATA_FILES,
    # Other options
    options={'py2app': OPTIONS},
    # Requirements
    setup_requires=['py2app'],
)

# archive entire app into disk image
p = Popen(['hdiutil', 'create', os.path.join('dist', APP_NAME + '.dmg'),
           '-srcfolder', os.path.join('dist', APP_NAME + '.app')],
          stdout=PIPE, stdin=PIPE, stderr=PIPE)
p.wait()
print p.stdout.read()
print p.stderr.read()
